# seconds
delay: 5
world:
  - "world"
immune-armor:
  - 298
  - 136
  - 314
effects:
  -
    id: 2
    # seconds
    duration: 6
    amplifier: 2
  -
    id: 9
    duration: 8
    amplifier: 0
  -
    id: 17
    duration: 10
    amplifier: 1
  -
    id: 18
    duration: 9
    amplifier: 1
  -
    id: 19
    duration: 5
    amplifier: 0
